M48
; DRILL file {KiCad 9.0.2} date 2025-07-06T22:42:41-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-06T22:42:41-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
%
G90
G05
T1
X142.51Y-47.765
X148.29Y-47.765
T2
X89.18Y-110.0
X97.78Y-110.0
X178.0Y-110.0
X186.6Y-110.0
M30
